openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /price:
    get:
      tags:
        - Prices
      operationId: getPrice
      parameters:
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: appDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        "404":
          description: NOT FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionErrorResponse'
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExceptionErrorResponse'
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: double
    ExceptionErrorResponse:
      type: object
      properties:
        type:
          type: string
          example: NOT FOUND
        message:
          type: string
          example: Required request parameter 'brandId' for method parameter type Long is not present